/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseLabel: typeof import('./src/components/BaseLabel.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    HeaderLogo: typeof import('./src/components/HeaderLogo.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    PageColumn: typeof import('./src/components/PageColumn.vue')['default']
    PageColumnBody: typeof import('./src/components/PageColumnBody.vue')['default']
    PageColumnControls: typeof import('./src/components/PageColumnControls.vue')['default']
    PostsListItem: typeof import('./src/components/PostsListItem.vue')['default']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RefreshButton: typeof import('./src/components/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusItem: typeof import('./src/components/StatusItem.vue')['default']
    TheAboutDialog: typeof import('./src/components/TheAboutDialog.vue')['default']
    TheCategorySelect: typeof import('./src/components/TheCategorySelect.vue')['default']
    TheCommentsColumnBody: typeof import('./src/components/TheCommentsColumnBody.vue')['default']
    TheCommentsColumnTitle: typeof import('./src/components/TheCommentsColumnTitle.vue')['default']
    TheLegalDialog: typeof import('./src/components/TheLegalDialog.vue')['default']
    TheLinkColumnBody: typeof import('./src/components/TheLinkColumnBody.vue')['default']
    TheLinkColumnTitle: typeof import('./src/components/TheLinkColumnTitle.vue')['default']
    TheNoSelectionColumn: typeof import('./src/components/TheNoSelectionColumn.vue')['default']
    ThePostColumns: typeof import('./src/components/ThePostColumns.vue')['default']
    ThePostsListColumn: typeof import('./src/components/ThePostsListColumn.vue')['default']
    ThePostsListColumnBody: typeof import('./src/components/ThePostsListColumnBody.vue')['default']
    ThePrimaryColumn: typeof import('./src/components/ThePrimaryColumn.vue')['default']
    TheSecondaryColumn: typeof import('./src/components/TheSecondaryColumn.vue')['default']
    TheSettingsMenu: typeof import('./src/components/TheSettingsMenu.vue')['default']
    TheUnifiedViewControl: typeof import('./src/components/TheUnifiedViewControl.vue')['default']
  }
}
