/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseLabel: typeof import('./src/components/base/BaseLabel.vue')['default']
    BaseStatusIndicator: typeof import('./src/components/base/BaseStatusIndicator.vue')['default']
    BaseSVGFilters: typeof import('./src/components/base/BaseSVGFilters.vue')['default']
    CommentItem: typeof import('./src/components/column-post/comments/CommentItem.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    PageColumn: typeof import('./src/components/page/PageColumn.vue')['default']
    PageColumnBody: typeof import('./src/components/page/PageColumnBody.vue')['default']
    PageColumnControls: typeof import('./src/components/page/PageColumnControls.vue')['default']
    PostsListItem: typeof import('./src/components/column-posts-list/PostsListItem.vue')['default']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAboutDialog: typeof import('./src/components/column-posts-list/settings/TheAboutDialog.vue')['default']
    TheCategorySelect: typeof import('./src/components/column-posts-list/header/TheCategorySelect.vue')['default']
    TheCommentsColumnBody: typeof import('./src/components/column-post/comments/TheCommentsColumnBody.vue')['default']
    TheCommentsColumnTitle: typeof import('./src/components/column-post/comments/TheCommentsColumnTitle.vue')['default']
    TheHeaderLogo: typeof import('./src/components/column-posts-list/header/TheHeaderLogo.vue')['default']
    TheLegalDialog: typeof import('./src/components/column-posts-list/settings/TheLegalDialog.vue')['default']
    TheLinkColumnBody: typeof import('./src/components/column-post/link/TheLinkColumnBody.vue')['default']
    TheLinkColumnTitle: typeof import('./src/components/column-post/link/TheLinkColumnTitle.vue')['default']
    TheNoSelectionColumn: typeof import('./src/components/column-post/TheNoSelectionColumn.vue')['default']
    ThePostColumns: typeof import('./src/components/column-post/ThePostColumns.vue')['default']
    ThePostsListColumn: typeof import('./src/components/column-posts-list/ThePostsListColumn.vue')['default']
    ThePostsListColumnBody: typeof import('./src/components/column-posts-list/ThePostsListColumnBody.vue')['default']
    ThePrimaryColumn: typeof import('./src/components/column-post/ThePrimaryColumn.vue')['default']
    TheRefreshButton: typeof import('./src/components/column-posts-list/header/TheRefreshButton.vue')['default']
    TheSecondaryColumn: typeof import('./src/components/column-post/TheSecondaryColumn.vue')['default']
    TheSettingsMenu: typeof import('./src/components/column-posts-list/settings/TheSettingsMenu.vue')['default']
    TheUnifiedViewControl: typeof import('./src/components/column-post/TheUnifiedViewControl.vue')['default']
  }
}
